/*
 * File: app/view/LoginForm.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.LoginForm', {
    extend: 'Ext.form.Panel',

    height: 178,
    width: 322,
    bodyPadding: 10,
    title: 'Cab-O-Meter Login',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    maxWidth: 250,
                    fieldLabel: 'Emp ID',
                    allowBlank: false,
                    disableKeyFilter: false,
                    size: 10
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    maxWidth: 250,
                    width: 588,
                    fieldLabel: 'Password',
                    hideLabel: false,
                    allowBlank: false
                },
                {
                    xtype: 'button',
                    width: 57,
                    allowDepress: false,
                    arrowAlign: 'bottom',
                    enableToggle: false,
                    pressed: false,
                    text: 'Login'
                },
                {
                    xtype: 'button',
                    width: 124,
                    text: 'Forget Password'
                }
            ]
        });

        me.callParent(arguments);
    }

});