/*
 * File: app/view/ManagerView.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ManagerView', {
    extend: 'Ext.form.Panel',

    height: 579,
    width: 666,
    bodyPadding: 10,
    title: 'Manager View',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    height: 105,
                    items: [
                        {
                            xtype: 'datefield',
                            fieldLabel: 'From Date'
                        },
                        {
                            xtype: 'datefield',
                            fieldLabel: 'To Date'
                        },
                        {
                            xtype: 'button',
                            width: 100,
                            text: 'Go'
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    height: 358,
                    width: 637,
                    activeTab: 1,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Unapproved Requests',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    title: '',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: 'Request ID'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: 'Requested by'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'number',
                                            text: 'Estimated trip Cost'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            dataIndex: 'date',
                                            text: 'Date'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            dataIndex: 'bool',
                                            text: 'Reason'
                                        },
                                        {
                                            xtype: 'actioncolumn',
                                            items: [
                                                {

                                                },
                                                {

                                                }
                                            ]
                                        }
                                    ],
                                    viewConfig: {
                                        plugins: [
                                            Ext.create('Ext.grid.plugin.DragDrop', {
                                                ptype: 'gridviewdragdrop'
                                            })
                                        ]
                                    },
                                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                                    })
                                },
                                {
                                    xtype: 'textareafield',
                                    width: 639,
                                    fieldLabel: 'Approve/Reject Comments'
                                },
                                {
                                    xtype: 'button',
                                    formBind: true,
                                    text: 'Approve'
                                },
                                {
                                    xtype: 'button',
                                    formBind: true,
                                    text: 'Reject'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            height: 57,
                            title: 'Approved Request',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    height: 210,
                                    width: 633,
                                    title: '',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            width: 88,
                                            dataIndex: 'string',
                                            text: 'Request ID'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'number',
                                            text: 'Resource Name'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            dataIndex: 'date',
                                            text: 'Requested Date'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            dataIndex: 'bool',
                                            text: 'Boolean'
                                        }
                                    ],
                                    viewConfig: {

                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Declined Requests',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    title: '',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: 'String'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'number',
                                            text: 'Number'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            dataIndex: 'date',
                                            text: 'Date'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            dataIndex: 'bool',
                                            text: 'Boolean'
                                        }
                                    ],
                                    viewConfig: {

                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});