CREATE TABLE employee (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id VARCHAR(10) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    middle_name VARCHAR(50) NULL,
    role VARCHAR(25) NOT NULL,
    cost_centre VARCHAR(20) NOT NULL,
    team_name VARCHAR(100) NOT NULL,
    contact_no VARCHAR(10) NOT NULL,
    alternate_contact_no VARCHAR(10) NULL,
    landline_no VARCHAR(10) NULL,
    email VARCHAR(100) NOT NULL,
    manager_id VARCHAR(10) NULL,
    gender VARCHAR(10) NOT NULL,
    password VARCHAR(100) NOT NULL DEFAULT 'password',
    CONSTRAINT employee_employee_id_uq UNIQUE (emp_id),
    CONSTRAINT employee_email_id_uq UNIQUE (email)
);

CREATE TABLE address (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    addr_line1 VARCHAR(50) NOT NULL,
    addr_line2 VARCHAR(100) NULL,
    locality VARCHAR(25) NOT NULL,
    city VARCHAR(25) NOT NULL,
    state VARCHAR(20) NOT NULL,
    landmark1 VARCHAR(50) NOT NULL,
    landmark2 VARCHAR(50) NULL,
    employee_id INTEGER NOT NULL REFERENCES employee (id)
);

CREATE TABLE cab_request (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL REFERENCES employee (id),
    create_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    update_date TIMESTAMPTZ NULL,
    created_by VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    login_time TIME NOT NULL,
    end_date DATE NOT NULL,
    logout_time TIME NOT NULL,
    req_reason VARCHAR(1000) NULL,
    preapproved CHAR(1) NULL,
    isapproved CHAR(1) NULL,
    approver_id VARCHAR(10) NULL,
    appr_reason VARCHAR(1000) NULL,
    reocurr_days VARCHAR(80) NULL
);

CREATE TABLE request_cancellation (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id INTEGER NOT NULL REFERENCES cab_request (id),
    employee_id INTEGER NOT NULL REFERENCES employee (id),
    iscomp_req_cancelled CHAR(1) NULL,
    cancelled_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    cancelled_by VARCHAR(10) NOT NULL,
    canc_reason VARCHAR(500) NULL,
    update_time TIMESTAMPTZ NULL,
    forfeit_cancel_req CHAR(1) NULL
);

CREATE TABLE driver_info (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_name VARCHAR(100) NOT NULL,
    agency_name VARCHAR(20) NULL,
    license_no VARCHAR(20) NULL,
    license_expiry_date DATE NULL,
    contact_no VARCHAR(15) NOT NULL,
    addr_line1 VARCHAR(50) NOT NULL,
    addr_line2 VARCHAR(50) NULL,
    locality VARCHAR(25) NOT NULL,
    city VARCHAR(25) NOT NULL,
    state VARCHAR(20) NOT NULL
);

CREATE TABLE cab_info (
    registration_number VARCHAR(20) PRIMARY KEY,
    agency_name VARCHAR(20) NOT NULL,
    model_name VARCHAR(20) NULL,
    make VARCHAR(20) NULL,
    capacity INTEGER NOT NULL,
    make_year INTEGER NULL,
    rateperhr DOUBLE PRECISION NULL,
    fc_valid_until DATE NULL,
    default_driver_id INTEGER NULL REFERENCES driver_info (id)
);

CREATE TABLE trip_plan (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_date DATE NOT NULL,
    trip_time TIME NOT NULL,
    route_name VARCHAR(50) NOT NULL,
    approx_trip_kms INTEGER NULL,
    approx_trip_cost DOUBLE PRECISION NOT NULL,
    toll_charges DOUBLE PRECISION NULL,
    pickup_drop CHAR(1) NULL,
    cab_regd_number VARCHAR(20) NULL REFERENCES cab_info (registration_number),
    driver_id INTEGER NULL REFERENCES driver_info (id)
);

CREATE TABLE trip_passengers (
    trip_plan_id INTEGER NOT NULL REFERENCES trip_plan (id),
    employee_id VARCHAR(10) NOT NULL,
    employee_name VARCHAR(100) NOT NULL,
    location VARCHAR(60) NOT NULL,
    address VARCHAR(200) NULL,
    distance_in_kms INTEGER NULL,
    trip_sequence INTEGER NULL,
    approved_manager_id VARCHAR(10) NOT NULL,
    approved_manager_name VARCHAR(100) NOT NULL,
    cost_centre VARCHAR(20) NOT NULL,
    split_cost DOUBLE PRECISION NULL,
    team_name VARCHAR(100) NOT NULL
);

CREATE TABLE trip (
    trip_plan_id INTEGER PRIMARY KEY REFERENCES trip_plan (id),
    trip_date DATE NOT NULL,
    trip_time TIME NOT NULL,
    cab_regd_number VARCHAR(20) NOT NULL REFERENCES cab_info (registration_number),
    driver_id INTEGER NOT NULL REFERENCES driver_info (id),
    route_name VARCHAR(50) NOT NULL,
    trip_kms INTEGER NULL,
    trip_cost DOUBLE PRECISION NOT NULL,
    toll_charges DOUBLE PRECISION NULL
);

CREATE INDEX driver_info_driver_name_idx ON driver_info (driver_name);
CREATE INDEX cab_request_employee_id_idx ON cab_request (employee_id);
CREATE INDEX cab_request_dates_idx ON cab_request (start_date, end_date);
