CREATE TABLE driver_info (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DRIVER_NAME VARCHAR(100) NOT NULL,
	AGENCY_NAME VARCHAR(20) NULL,
	LICENSE_NO VARCHAR(20) NULL,
	LICENSE_EXPIRY_DATE DATE  NULL,
	CONTACT_NO INT(10) NOT NULL,
	ADDR_LINE1 VARCHAR(50) NOT NULL,
	ADDR_LINE2 VARCHAR(50)  NULL,
	LOCALITY VARCHAR(25) NOT NULL,
	CITY VARCHAR(25) NOT NULL,
	STATE VARCHAR(20) NOT NULL
) ENGINE = InnoDB ROW_FORMAT = DEFAULT;

CREATE TABLE cab_info (
	REGISTRATION_NUMBER  VARCHAR(20) PRIMARY KEY NOT NULL,
	AGENCY_NAME VARCHAR(20) NOT NULL,
	MODEL_NAME VARCHAR(20) NULL,
	MAKE VARCHAR(20) NULL,
	CAPACITY INT(2) NOT NULL,
	MAKE_YEAR INT(4) NULL,
	RATEPERHR FLOAT NULL,
	FC_VALID_UNTIL DATE  NULL,
	DEFAULT_DRIVER_ID INT NULL
) ENGINE = InnoDB ROW_FORMAT = DEFAULT;

ALTER TABLE driver_info ADD INDEX driver_info_driver_name_idx (DRIVER_NAME);
ALTER TABLE cab_info  ADD CONSTRAINT cab_info_default_driver_id_fk FOREIGN KEY (DEFAULT_DRIVER_ID) REFERENCES driver_info(ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
