CREATE TABLE trip_plan (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TRIP_DATE DATE NOT NULL,
	TRIP_TIME TIME NOT NULL,
	ROUTE_NAME  VARCHAR(50) NOT NULL,
	APPROX_TRIP_KMS INT NULL,
	APPROX_TRIP_COST FLOAT(10) NOT NULL,
	TOLL_CHARGES FLOAT(10) NULL,
	PICKUP_DROP  CHAR(1) ASCII NULL
) ENGINE = InnoDB ROW_FORMAT = DEFAULT;

CREATE TABLE trip_passengers(
	TRIP_PLAN_ID INT NOT NULL,
	EMPLOYEE_ID VARCHAR(10) NOT NULL,
	EMPLOYEE_NAME VARCHAR(100) NOT NULL,
	LOCATION VARCHAR(60) NOT NULL,
	ADDRESS VARCHAR(200) NULL,
	DISTANCE_IN_KMS INT NULL,
	TRIP_SEQUENCE INT NULL,
	APPROVED_MANAGER_ID VARCHAR(10) NOT NULL,
	APPROVED_MANAGER_NAME VARCHAR(100) NOT NULL,
	COST_CENTRE INT(20) NOT NULL,
	SPLIT_COST FLOAT(10) NULL,
	TEAM_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE trip (
	TRIP_PLAN_ID INT NOT NULL PRIMARY KEY,
	TRIP_DATE DATE NOT NULL,
	TRIP_TIME TIME NOT NULL,
	CAB_REGD_NUMBER VARCHAR(20) NOT NULL,
	DRIVER_ID INT NOT NULL,
	ROUTE_NAME  VARCHAR(50) NOT NULL,
	TRIP_KMS INT NULL,
	TRIP_COST FLOAT(10) NOT NULL,
	TOLL_CHARGES FLOAT(10) NULL
) ENGINE = InnoDB ROW_FORMAT = DEFAULT;

--ALTER TABLE trip_passengers ADD CONSTRAINT trip_passengers_employee_id_fk FOREIGN KEY (EMPLOYEE_ID) REFERENCES employee(ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE trip_passengers ADD CONSTRAINT trip_passengers_trip_plan_id_fk FOREIGN KEY (TRIP_PLAN_ID) REFERENCES trip_plan(ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE trip ADD CONSTRAINT trip_trip_plan_fk FOREIGN KEY (TRIP_PLAN_ID) REFERENCES trip_plan(ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE trip ADD CONSTRAINT trip_cab_info_fk FOREIGN KEY (CAB_REGD_NUMBER) REFERENCES cab_info(REGISTRATION_NUMBER) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE trip ADD CONSTRAINT trip_driver_info_fk FOREIGN KEY (DRIVER_ID) REFERENCES driver_info(ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

